# Generated by Django 4.0.2 on 2022-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('password', models.CharField(blank=True, max_length=70)),
                ('contact', models.CharField(blank=True, max_length=70)),
            ],
        ),
    ]
